### ISSUE TITLE
Function throws EPSG code

### ISSUE THREAD

**Issue by m-mohr** [DanielJDufour/reproject-bbox#3]
If I call
```
reprojectBoundingBox({
  "bbox": [
    9.0010573796,
    51.9985704523422,
    9.0038629351578,
    52.0013760079
  ],
  "from": 32767,
  "to": 4326,
  "density": 100
})
```
it throws an exception that is just the string "EPSG:32767" :-o

**Comment by DanielJDufour** [comment]
32767 is "user-defined" projection according to GeoTIFF spec: http://geotiff.maptools.org/spec/geotiff6.html

This can happen in 2 cases I know about (but probably more too):
- User used an ESRI product to create the GeoTIFF.  ESRI doesn't want to provide an EPSG code, so it sets 32767 as the PROJCS code in the geotiff AND provides an ESRI Projection Engine string (like WKT) in an ascii metadata tag.  See https://github.com/GeoTIFF/test-data/blob/main/files/gadas.tif
- User is doing some really awesome scientific analysis very specific to an area (like Antarctica or Mars) and because no known EPSG projection works for them, they define their own projection using their own custom affine transformation.

**Comment by DanielJDufour** [comment]
I'm not sure on the best solution, should reproject-bbox be updated to accept a proj4js string or wkt string (wouldn't be too difficult I think) in the from or to params?

**Comment by DanielJDufour** [comment]
But it'll then be left up to the user to find a way to parse and pass in the proj4js string / wkt.

**Comment by DanielJDufour** [comment]
fwiw, this lib: https://github.com/geotiff/geotiff-epsg-code can be helpful with fixing the first use case (ESRI not using the standard epsg code), but won't fix the totally custom use case

**Comment by m-mohr** [comment]
I think it would be good enough if it would not just throw a string, but instead throw either an error with a more useful message or return null or so.
I was more confused that I did not get an actual error object which I could check the stacktrace or so...

**Comment by DanielJDufour** [comment]
for sure, will do! :-)

**Comment by m-mohr** [comment]
Thanks.

**Comment by DanielJDufour** [comment]
done. new version of reproject-bbox published

**Comment by DanielJDufour** [comment]
also updated docs with wkt and proj4js example
